package com.boylab.greendaodemo.db.tableDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.boylab.greendaodemo.db.table.Fruit;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRUIT".
*/
public class FruitDao extends AbstractDao<Fruit, Long> {

    public static final String TABLENAME = "FRUIT";

    /**
     * Properties of entity Fruit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Price = new Property(2, float.class, "price", false, "PRICE");
        public final static Property Weigh = new Property(3, float.class, "weigh", false, "WEIGH");
        public final static Property Color = new Property(4, String.class, "color", false, "COLOR");
    }


    public FruitDao(DaoConfig config) {
        super(config);
    }
    
    public FruitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRUIT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"PRICE\" REAL NOT NULL ," + // 2: price
                "\"WEIGH\" REAL NOT NULL ," + // 3: weigh
                "\"COLOR\" TEXT);"); // 4: color
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRUIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Fruit entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindDouble(3, entity.getPrice());
        stmt.bindDouble(4, entity.getWeigh());
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(5, color);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Fruit entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindDouble(3, entity.getPrice());
        stmt.bindDouble(4, entity.getWeigh());
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(5, color);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Fruit readEntity(Cursor cursor, int offset) {
        Fruit entity = new Fruit( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getFloat(offset + 2), // price
            cursor.getFloat(offset + 3), // weigh
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // color
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Fruit entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrice(cursor.getFloat(offset + 2));
        entity.setWeigh(cursor.getFloat(offset + 3));
        entity.setColor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Fruit entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Fruit entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Fruit entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
