package com.boylab.greendaodemo.db.tableDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.boylab.greendaodemo.db.table.JoinTeachers;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_TEACHER_TO_STUDENT".
*/
public class JoinTeacherToStudentDao extends AbstractDao<JoinTeachers, Long> {

    public static final String TABLENAME = "JOIN_TEACHER_TO_STUDENT";

    /**
     * Properties of entity JoinTeacherToStudent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tid = new Property(1, Long.class, "tid", false, "TID");
        public final static Property Sid = new Property(2, Long.class, "sid", false, "SID");
    }


    public JoinTeacherToStudentDao(DaoConfig config) {
        super(config);
    }
    
    public JoinTeacherToStudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_TEACHER_TO_STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TID\" INTEGER," + // 1: tid
                "\"SID\" INTEGER);"); // 2: sid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_TEACHER_TO_STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinTeachers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long tid = entity.getTid();
        if (tid != null) {
            stmt.bindLong(2, tid);
        }
 
        Long sid = entity.getSid();
        if (sid != null) {
            stmt.bindLong(3, sid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinTeachers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long tid = entity.getTid();
        if (tid != null) {
            stmt.bindLong(2, tid);
        }
 
        Long sid = entity.getSid();
        if (sid != null) {
            stmt.bindLong(3, sid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinTeachers readEntity(Cursor cursor, int offset) {
        JoinTeachers entity = new JoinTeachers( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // tid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // sid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinTeachers entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSid(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinTeachers entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinTeachers entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinTeachers entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
